<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap06_Ex6-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

練習問題6-2

In [10]:
hier_dfl = DataFrame(
    np.arange(12).reshape((3,4)),
    index = [['c','d','d'],[1,2,1]],
    columns = [['Kyoto','Nagoya','Hokkaido','Kyoto'],['Yellow','Yellow','Red','Blue']
    ]
)

hier_dfl.index.names = ['key1','key2']
hier_dfl.columns.names = ['city','color']
hier_dfl

city       Kyoto Nagoya Hokkaido Kyoto
color     Yellow Yellow      Red  Blue
key1 key2
c    1         0      1        2     3
d    2         4      5        6     7
     1         8      9       10    11

In [14]:
hier_dfl.groupby(level='city', axis=1).mean()

/tmp/ipykernel_2226/3593754561.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_dfl.groupby(level='city', axis=1).mean()

city       Hokkaido  Kyoto  Nagoya
key1 key2
c    1          2.0    1.5     1.0
d    2          6.0    5.5     5.0
     1         10.0    9.5     9.0