<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/chap06_Ex6-9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
sns.set()
%matplotlib inline

#小数第3位まで表示
%precision 3

'%.3f'

In [2]:
!mkdir chap3
!cd ./chap3

In [3]:
#webからデータを取得したら、zipファイルを取り扱うためのライブラリ
import requests, zipfile
from io import StringIO
import io

In [4]:
#データがあるurlの確定
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00356/student.zip'

#データをurlから取得する
r =requests.get(url, stream=True)

#zipfileを読み込み展開する
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [5]:
ls

chap3/        student-mat.csv  student-por.csv
sample_data/  student-merge.R  student.txt

In [6]:
student_data_math = pd.read_csv('student-mat.csv')

In [7]:
import pandas as pd
student_data_math = pd.read_csv('student-mat.csv',sep=';')
student_data_math['age_d'] = student_data_math['age'].map(lambda x: x*2)
student_data_math.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,age_d
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,36
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,34
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,30
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,30
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,32

In [11]:
pd.value_counts(pd.qcut(student_data_math.absences,3))

/tmp/ipykernel_3970/372418432.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(pd.qcut(student_data_math.absences,3))

absences
(-0.001, 2.0]    183
(6.0, 75.0]      115
(2.0, 6.0]        97
Name: count, dtype: int64